### ISSUE TITLE
Can't import alt-shared. Compilation fails with an error.

### ISSUE THREAD

**Issue by JustCup** [altmp/altv-js-bytecode#2]
### Description of the problem
When I import a file containing `import * as shared from 'alt-shared';`, for example. I get the following warning and an error in server console:
```
[17:34:15][Warning] Full paths without / in the beginning are deprecated. Consider starting your paths with /
[17:34:15][Error] [V8 Bytecode]  File not found: 
```
### Reproduction steps
On the client side: 
```
import * as shared from 'alt-shared';

shared.log('The compilation will crash.');
```
### Operating system
`Windows 10`
### Version
`release/9.5`

**Comment by FabianTerhorst** [comment]
You can add it to this array and do a pull request: https://github.com/altmp/altv-js-bytecode/blob/138d667c99cc00821b5b99f9e48be40e7a8b213a/module/src/runtime.cpp#L30
