### ISSUE TITLE
std::bad_alloc on linux 

### ISSUE THREAD

**Issue by Shino58** [altmp/altv-js-bytecode#6]
**Description of the problem**

When i use on linux this make an std::bad_alloc but on windows thats working properly

```
[03:27:26] [V8 Bytecode] Converted file to bytecode: client/utility/flags.js
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
--Type <RET> for more, q to quit, c to continue without paging--bt

Thread 1 "altv-server" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.

```

**Reproduction steps**
I just use it on linux

**Operating system**
Debian 11 lite on docker

**Version**
release/10.2

**Comment by ThomasMarangoni** [comment]
Can you link the docker image you are depending on?

**Comment by Shino58** [comment]
i use my own image based on debian:bullseye-slim
